### ISSUE TITLE
program does not work with -i when a song.sql already exists

### ISSUE THREAD

**Issue by Fingadumbledore** [CCC-Jugendgruppe/python_mp3#15]
ERROR: Database file does not exist

**Comment by LeSnake04** [comment]
Upsi, I forgot a not here: 9fa37a3bad7956025af00486c0e139587cb047b6

**Comment by hyperbel** [comment]
I tried adding the `not?` to `if os.path.exists(db_file):`, but the change doesn't change anything for me when running with -g argument.

**Comment by Konradrundfunk** [comment]
@datewat can you provide more context? How does the modified code look like and what commands did you actually run. Also a stacktrace would be helpful.

**Comment by hyperbel** [comment]
I ran `python3 python_mp3/main.py -g` in the terminal. The code now is: 
```
def __init__(self, db_file):
		if not os.path.exists(db_file):
			print("ERROR: Database file does not exist")
			sys.exit(3)
```

It's not an actual exception, but only prints the error. Also, for some reason the debugging doesn't work correctly, so the debugger doesn't break at breakpoints outside of the main.py file. I'm sorry, but I am unable to provide the stack trace for aforementioned reason.

**Comment by Konradrundfunk** [comment]
Try setting the -o flag and see weather it works. The error could be that the python runtime env can't get hold of the standart file and therefore throws this error.
